# Generated by Django 6.0 on 2026-02-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='layout_template',
            field=models.JSONField(blank=True, default=dict, help_text="JSON layout config: {'seat_classes': [{'class_id': 1, 'rows': 10, 'columns': 6}, ...]}"),
        ),
    ]
