# Generated by Django 6.0 on 2026-02-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aircraft_layout_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='layout_template',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"seat_classes": [{"class_id": 1, "rows": 10, "columns": 6}, ...]}'),
        ),
    ]
