# Generated by Django 6.0 on 2026-01-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='column',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_extra_legroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_aisle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_bulkhead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_exit_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_window',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price for premium seats', max_digits=10),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.schedule'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.seatclass'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['schedule', 'seat_class'], name='app_seat_schedul_6fa18a_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['schedule', 'row', 'column'], name='app_seat_schedul_3b04f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('schedule', 'row', 'column'), name='unique_position_per_schedule'),
        ),
    ]
