# Generated by Django 6.0 on 2026-01-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seat_column_seat_has_extra_legroom_seat_is_aisle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Meal Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssistanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('wheelchair', 'Wheelchair Assistance'), ('boarding', 'Pre-boarding Assistance'), ('medical', 'Medical Assistance'), ('unaccompanied_minor', 'Unaccompanied Minor'), ('pet', 'Pet Travel Assistance'), ('other', 'Other Special Assistance')], default='wheelchair', max_length=50)),
                ('level', models.CharField(choices=[('basic', 'Basic Assistance'), ('standard', 'Standard Assistance'), ('premium', 'Premium Assistance')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('requires_advance_notice', models.PositiveIntegerField(default=48, help_text='Hours of advance notice required')),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_included', models.BooleanField(default=True, help_text='Is this service included in the base fare?')),
                ('passenger_type_applicable', models.CharField(choices=[('all', 'All'), ('adults_only', 'Adults Only'), ('children_only', 'Children Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_services', to='app.airline')),
            ],
            options={
                'verbose_name_plural': 'Assistance Services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='assistance_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_links', to='app.assistanceservice'),
        ),
        migrations.CreateModel(
            name='BaggageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight_kg', models.IntegerField(choices=[(0, 'No Extra'), (5, '5kg'), (10, '10kg'), (15, '15kg'), (20, '20kg'), (25, '25kg'), (30, '30kg'), (32, '32kg'), (40, '40kg')], default=0)),
                ('dimensions', models.CharField(blank=True, help_text='e.g., 158cm (L+W+H)', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_included', models.BooleanField(default=False, help_text='Is this baggage included in the base fare?')),
                ('applies_domestic', models.BooleanField(default=True)),
                ('applies_international', models.BooleanField(default=True)),
                ('passenger_type_applicable', models.CharField(choices=[('all', 'All'), ('adults_only', 'Adults Only'), ('children_only', 'Children Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggage_options', to='app.airline')),
            ],
            options={
                'ordering': ['display_order', 'weight_kg'],
                'unique_together': {('airline', 'weight_kg')},
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='baggage_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_links', to='app.baggageoption'),
        ),
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('meal_type', models.CharField(choices=[('standard', 'Standard'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('gluten_free', 'Gluten Free'), ('child', "Child's Meal"), ('infant', "Infant's Meal")], default='standard', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_included', models.BooleanField(default=False, help_text='Is this meal included in the base fare?')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Approximate calories', null=True)),
                ('contains', models.TextField(blank=True, help_text='Ingredients/contents', null=True)),
                ('allergens', models.TextField(blank=True, help_text='Common allergens (nuts, dairy, etc.)', null=True)),
                ('available_on_domestic', models.BooleanField(default=True)),
                ('available_on_international', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_for_breakfast', models.BooleanField(default=True)),
                ('available_for_lunch', models.BooleanField(default=True)),
                ('available_for_dinner', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='app.airline')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mealcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('airline', 'name')},
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='meal_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_links', to='app.mealoption'),
        ),
    ]
