# Generated by Django 6.0 on 2026-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_aircraft_layout_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='special_type',
            field=models.CharField(blank=True, choices=[('exit_row', 'Exit Row'), ('wheelchair', 'Wheelchair Accessible'), ('unaccompanied_minor', 'Unaccompanied Minor'), ('nut_allergy', 'Nut Allergy Buffer'), ('bassinet', 'Bassinet Position')], help_text='Special seat designation for specific passenger needs', max_length=20, null=True),
        ),
    ]
