# Generated by Django 6.0 on 2026-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mealcategory_assistanceservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='passenger_type',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Infant', 'Infant')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('checkin', 'Ready for Check-in'), ('boarding', 'Boarding'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookingdetail',
            index=models.Index(fields=['status', 'booking_date'], name='app_booking_status_5578e3_idx'),
        ),
    ]
