# Generated by Django 6.0 on 2026-02-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_seat_special_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='special_type',
        ),
    ]
