# Generated by Django 6.0 on 2026-01-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bookingdetail_passenger_type_bookingdetail_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerinfo',
            name='gender',
        ),
        migrations.AddField(
            model_name='passengerinfo',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='MR', max_length=10),
        ),
    ]
