# Generated by Django 6.0 on 2026-02-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_seat_special_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='special_type',
            field=models.CharField(blank=True, choices=[('exit_row', 'Exit Row'), ('wheelchair', 'Wheelchair Accessible'), ('unaccompanied_minor', 'Unaccompanied Minor'), ('nut_allergy', 'Nut Allergy Buffer'), ('bassinet', 'Bassinet Position')], help_text='Special seat designation for specific passenger needs', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['schedule', 'special_type'], name='app_seat_schedul_c31a7b_idx'),
        ),
    ]
