# Generated by Django 6.0 on 2026-01-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_passengerinfo_gender_passengerinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
