# Generated by Django 6.0 on 2026-02-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_seat_special_type_seat_app_seat_schedul_c31a7b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seat',
            name='app_seat_schedul_c31a7b_idx',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='special_type',
        ),
    ]
