# Generated by Django 6.0 on 2026-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_seat_app_seat_schedul_c31a7b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='has_bassinet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_nut_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_unaccompanied_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
