# Generated by Django 6.0 on 2026-02-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_seat_has_bassinet_seat_has_nut_allergy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='has_bassinet',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='has_nut_allergy',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_unaccompanied_minor',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_wheelchair_accessible',
        ),
    ]
