# Generated by Django 6.0 on 2026-01-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount from frontend calculation', max_digits=10),
        ),
    ]
