# Generated by Django 6.0 on 2026-02-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_seat_has_bassinet_remove_seat_has_nut_allergy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='has_bassinet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_nut_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_unaccompanied_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
