# Generated by Django 6.0 on 2026-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_seat_has_bassinet_seat_has_nut_allergy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='price_adjustment',
        ),
        migrations.AddField(
            model_name='seat',
            name='price_adjustment_auto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automatic price adjustment based on seat features', max_digits=10),
        ),
        migrations.AddField(
            model_name='seat',
            name='price_adjustment_manual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Manual price adjustment by admin', max_digits=10),
        ),
    ]
