# Generated by Django 6.0 on 2026-01-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_booking_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatClassFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.seatclass')),
            ],
            options={
                'ordering': ['seat_class', 'display_order'],
                'unique_together': {('seat_class', 'feature')},
            },
        ),
    ]
