# Generated by Django 6.0 on 2026-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_seatclassfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
