# Generated by Django 6.0 on 2026-01-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_seatclass_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatclass',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='app.airline'),
        ),
    ]
