# Generated by Django 6.0 on 2026-01-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
