# Generated by Django 6.0 on 2026-02-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_students_date_of_birth_students_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='students',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='students',
            name='passport_number',
        ),
    ]
