# Generated by Django 6.0 on 2026-02-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_students_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ml_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ML predicted base price (saved from predictor)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ml_price_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the ML price was last calculated', null=True),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['ml_base_price', 'status'], name='app_schedul_ml_base_73b80a_idx'),
        ),
    ]
