# Generated by Django 6.0 on 2026-02-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_add_ml_price_fields_to_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_user_factor', models.DecimalField(decimal_places=2, default=1.05, max_digits=5)),
                ('new_user_factor', models.DecimalField(decimal_places=2, default=1.03, max_digits=5)),
                ('returning_user_factor', models.DecimalField(decimal_places=2, default=0.97, max_digits=5)),
                ('loyal_user_factor', models.DecimalField(decimal_places=2, default=0.92, max_digits=5)),
                ('search_threshold_high', models.IntegerField(default=100)),
                ('search_threshold_medium', models.IntegerField(default=50)),
                ('search_threshold_low', models.IntegerField(default=20)),
                ('demand_factor_high', models.DecimalField(decimal_places=2, default=1.15, max_digits=5)),
                ('demand_factor_medium', models.DecimalField(decimal_places=2, default=1.08, max_digits=5)),
                ('demand_factor_low', models.DecimalField(decimal_places=2, default=1.03, max_digits=5)),
                ('days_departure_critical', models.IntegerField(default=3)),
                ('days_departure_near', models.IntegerField(default=7)),
                ('days_departure_medium', models.IntegerField(default=14)),
                ('days_departure_far', models.IntegerField(default=60)),
                ('days_factor_critical', models.DecimalField(decimal_places=2, default=1.25, max_digits=5)),
                ('days_factor_near', models.DecimalField(decimal_places=2, default=1.15, max_digits=5)),
                ('days_factor_medium', models.DecimalField(decimal_places=2, default=1.05, max_digits=5)),
                ('days_factor_far', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('peak_hour_factor', models.DecimalField(decimal_places=2, default=1.12, max_digits=5)),
                ('weekend_factor', models.DecimalField(decimal_places=2, default=1.08, max_digits=5)),
                ('peak_month_factor', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('holiday_factor', models.DecimalField(decimal_places=2, default=1.3, max_digits=5)),
                ('occupancy_high_threshold', models.DecimalField(decimal_places=2, default=0.8, max_digits=3)),
                ('occupancy_medium_threshold', models.DecimalField(decimal_places=2, default=0.6, max_digits=3)),
                ('occupancy_low_threshold', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('occupancy_factor_high', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('occupancy_factor_medium', models.DecimalField(decimal_places=2, default=1.1, max_digits=5)),
                ('occupancy_factor_low', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
    ]
