# Generated by Django 6.0 on 2026-02-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_pricingconfiguration'),
        ('fbs_instructor', '0007_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.ForeignKey(blank=True, help_text="Optional link to an instructor's activity", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='fbs_instructor.activity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
