# Generated by Django 6.0 on 2026-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_booking_activity_booking_is_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity_code_used',
            field=models.CharField(blank=True, help_text='The activity code that was used for this booking', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_practice',
            field=models.BooleanField(default=False, help_text='True if this is a practice booking (not graded)'),
        ),
    ]
