# Generated by Django 5.2.5 on 2026-02-20 15:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_booking_activity_code_used_booking_is_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookingtax',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_position_per_schedule',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price_adjustment',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"seat_classes": [{"class_id": 1, "rows": 10, "columns": 6}, ...]}'),
        ),
        migrations.AddField(
            model_name='bookingtax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_bassinet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_nut_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_unaccompanied_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='price_adjustment_auto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatic price adjustment based on seat features', max_digits=10),
        ),
        migrations.AddField(
            model_name='seat',
            name='price_adjustment_manual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual price adjustment by admin', max_digits=10),
        ),
        migrations.AddField(
            model_name='seatclass',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='seat',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='app.seatrequirement'),
        ),
    ]
