# Generated by Django 5.2.5 on 2026-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_seatrequirement_alter_bookingtax_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
