# Generated by Django 6.0 on 2026-02-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_students_gender'),
        ('app', '0026_booking_pnr'),
    ]

    operations = [
    ]
