# Generated by Django 6.0 on 2026-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_airport_latitude_airport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pnr',
            field=models.CharField(blank=True, help_text='6-character alphanumeric Passenger Name Record (GDS Locator)', max_length=6, null=True, unique=True),
        ),
    ]
