# Generated by Django 5.2.5 on 2026-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_booking_pnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='total_stops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
