# Generated by Django 5.2.5 on 2026-02-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_merge_students_gender_and_pnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinfo',
            name='ph_discount_type',
            field=models.CharField(choices=[('none', 'None'), ('senior', 'Senior Citizen'), ('pwd', 'PWD')], default='none', help_text='Philippine mandatory discounts (Senior Citizen/PWD)', max_length=10),
        ),
    ]
