# Generated by Django 6.0 on 2026-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_passengerinfo_ph_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the booking (activity) was submitted/confirmed', null=True),
        ),
    ]
