# Generated by Django 5.2.5 on 2026-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_passengerinfo_ph_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_session_id',
            field=models.CharField(blank=True, help_text='Temporary session ID used to hold seat locks', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_by_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
