# Generated by Django 5.2.5 on 2026-02-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_booking_booking_session_id_seat_locked_by_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airline_logos/'),
        ),
    ]
