# Generated by Django 5.2.5 on 2026-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_airline_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinfo',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
