# Generated by Django 5.2.5 on 2026-02-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_passengerinfo_passport_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
