# Generated by Django 5.2.5 on 2026-03-01 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_seat_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindetail',
            name='agent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='check_in_counter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='gate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='has_declared_safety',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked-in', 'Checked-In'), ('boarding', 'Boarding'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
