# Generated by Django 5.2.5 on 2026-03-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_checkindetail_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='gate',
            field=models.CharField(blank=True, help_text='Assigned gate for boarding, e.g. Gate 4A', max_length=20, null=True),
        ),
    ]
