# Generated by Django 5.2.5 on 2026-03-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_add_gate_to_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='gate',
            field=models.CharField(blank=True, default='Gate 7', max_length=10, null=True),
        ),
    ]
