# Generated by Django 5.2.5 on 2026-03-07 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_schedule_gate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Basic, Standard / Value, Flex / Plus', max_length=50)),
                ('type_code', models.CharField(help_text='e.g. basic, standard, flex', max_length=20)),
                ('markup_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat fee added to the base class price', max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG path or full SVG string for the icon', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('seat_class', models.ForeignKey(help_text='e.g. Economy', on_delete=django.db.models.deletion.CASCADE, related_name='fare_bundles', to='app.seatclass')),
            ],
            options={
                'ordering': ['display_order', 'markup_fee'],
                'unique_together': {('seat_class', 'type_code')},
            },
        ),
        migrations.CreateModel(
            name='FareBundleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('fare_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_features', to='app.farebundle')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
