# Generated by Django 6.0 on 2026-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:fbs_backend/app/migrations/0032_booking_submitted_at.py
        ('app', '0031_passengerinfo_ph_discount_type'),
========
        ('app', '0040_checkindetail_student'),
>>>>>>>> origin/doms:fbs_backend/app/migrations/0041_booking_submitted_at.py
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the booking (activity) was submitted/confirmed', null=True),
        ),
    ]
