# Generated by Django 5.2.5 on 2026-03-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_booking_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindetail',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='pwd_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='senior_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
