# Generated by Django 5.2.5 on 2026-03-11 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_checkindetail_passport_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkindetail',
            name='passport_expiry',
        ),
        migrations.RemoveField(
            model_name='checkindetail',
            name='pwd_id_number',
        ),
        migrations.RemoveField(
            model_name='checkindetail',
            name='senior_id_number',
        ),
    ]
