# Generated by Django 5.2.5 on 2026-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_tracklog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='layovers',
            field=models.JSONField(blank=True, default=list, help_text='List of layover objects: [{"code": "HKG", "city": "Hong Kong", "duration": "1h 30m"}]'),
        ),
    ]
