# Generated by Django 5.2.5 on 2026-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_flight_layovers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='layovers',
        ),
        migrations.AddField(
            model_name='flight',
            name='layovers_data',
            field=models.JSONField(blank=True, default=list, help_text='List of layovers: [{"airport": "HKG", "city": "Hong Kong", "duration": "1h 30m"}, ...]', null=True),
        ),
    ]
