# Generated by Django 5.2.5 on 2026-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_flight_layovers_flight_layovers_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('instructor', 'Instructor'), ('lms_admin', 'LMS Admin'), ('flight_admin', 'Flight Admin'), ('superadmin', 'Superadmin')], max_length=20, null=True),
        ),
    ]
