# Generated by Django 5.2.5 on 2026-03-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='fare_family_name',
            field=models.CharField(blank=True, help_text='The specific branded fare family name (e.g. Economy Flex)', max_length=100, null=True),
        ),
    ]
