# Generated by Django 5.2.5 on 2026-03-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_bookingdetail_fare_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='baggage_policy_type',
            field=models.CharField(choices=[('piece', 'Piece Concept'), ('weight', 'Weight Concept')], default='weight', max_length=10),
        ),
        migrations.AddField(
            model_name='airline',
            name='is_pooling_allowed',
            field=models.BooleanField(default=True, help_text='Whether baggage weight can be shared across passengers'),
        ),
        migrations.AddField(
            model_name='airline',
            name='max_baggage_pieces',
            field=models.IntegerField(default=1, help_text='Default piece limit for Piece Concept airlines'),
        ),
        migrations.AddField(
            model_name='farebundlefeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide or Phosphor icon name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farebundlefeature',
            name='is_meal_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farebundlefeature',
            name='is_priority_boarding_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farebundlefeature',
            name='is_seat_selection_included',
            field=models.BooleanField(default=False),
        ),
    ]
