# Generated by Django 5.2.5 on 2026-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_airline_baggage_policy_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='baggage_policy_type',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='is_pooling_allowed',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='max_baggage_pieces',
        ),
        migrations.RemoveField(
            model_name='farebundlefeature',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='farebundlefeature',
            name='is_meal_included',
        ),
        migrations.RemoveField(
            model_name='farebundlefeature',
            name='is_priority_boarding_included',
        ),
        migrations.RemoveField(
            model_name='farebundlefeature',
            name='is_seat_selection_included',
        ),
        migrations.AddField(
            model_name='seat',
            name='has_medical_oxygen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_pet_in_cabin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_sports_equipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='has_stretcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_deaf_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_large_persona',
            field=models.BooleanField(default=False),
        ),
    ]
