# Generated by Django 5.2.5 on 2026-04-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_airline_baggage_policy_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.CharField(blank=True, default='BSHM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='year_level',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
    ]
