# Generated by Django 5.2.5 on 2026-04-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_students_course_students_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mi',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
