[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "bookingapp"
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  VITE_API_URL = "https://fbs-vue.onrender.com"
