# Generated by Django 6.0 on 2026-01-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_students_options'),
        ('fbs_instructor', '0003_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='fbs_instructor.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollments', to='app.students')),
            ],
            options={
                'unique_together': {('section', 'student')},
            },
        ),
    ]
