# Generated by Django 6.0 on 2026-01-31 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_students_options'),
        ('fbs_instructor', '0004_sectionenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(default='Flight Booking', max_length=50)),
                ('required_trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_city', 'Multi City')], default='one_way', max_length=20)),
                ('required_origin', models.CharField(blank=True, max_length=100)),
                ('required_destination', models.CharField(blank=True, max_length=100)),
                ('required_departure_date', models.DateField(blank=True, null=True)),
                ('required_return_date', models.DateField(blank=True, null=True)),
                ('required_travel_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20)),
                ('required_passengers', models.PositiveIntegerField(default=1)),
                ('required_children', models.PositiveIntegerField(default=0)),
                ('required_infants', models.PositiveIntegerField(default=0)),
                ('require_passenger_details', models.BooleanField(default=True)),
                ('require_passport', models.BooleanField(default=False)),
                ('instructions', models.TextField()),
                ('total_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('due_date', models.DateTimeField()),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('addon_grading_enabled', models.BooleanField(default=True)),
                ('required_addon_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('activity_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('is_code_active', models.BooleanField(default=False)),
                ('code_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fbs_instructor.section')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('passenger_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], default='adult', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='fbs_instructor.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('quantity_per_passenger', models.PositiveIntegerField(default=1)),
                ('points_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_addons', to='fbs_instructor.activity')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addon')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_addons', to='fbs_instructor.activitypassenger')),
            ],
        ),
    ]
