# Generated by Django 6.0 on 2026-02-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_students_options'),
        ('fbs_instructor', '0005_activity_activitypassenger_activityaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStudentBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='assigned', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bindings', to='fbs_instructor.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_bindings', to='app.students')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
