# Generated by Django 6.0 on 2026-02-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0007_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypassenger',
            name='gender',
            field=models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.')], max_length=10),
        ),
    ]
