# Generated by Django 6.0 on 2026-02-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0008_alter_activitypassenger_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='grades_released',
            field=models.BooleanField(default=False),
        ),
    ]
