# Generated by Django 6.0 on 2026-02-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0009_activity_grades_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='fbs_instructor.activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
