# Generated by Django 6.0 on 2026-02-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0010_activitysegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
