# Generated by Django 6.0 on 2026-02-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0011_section_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
