# Generated by Django 6.0 on 2026-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0012_section_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='schedule',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
