# Generated by Django 5.2.5 on 2026-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0013_alter_section_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypassenger',
            name='passenger_category',
            field=models.CharField(choices=[('none', 'Regular'), ('senior', 'Senior Citizen'), ('pwd', 'PWD')], default='none', max_length=10),
        ),
    ]
