# Generated by Django 5.2.5 on 2026-02-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0014_activitypassenger_passenger_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=100)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbs_instructor.section')),
            ],
            options={
                'unique_together': {('section', 'schedule_id', 'date_sent')},
            },
        ),
    ]
