# Generated by Django 5.2.5 on 2026-03-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0015_schedulenotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystudentbinding',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
