# Generated by Django 5.2.5 on 2026-03-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0016_activitystudentbinding_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystudentbinding',
            name='rubric_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
