# Generated by Django 5.2.5 on 2026-03-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0017_activitystudentbinding_rubric_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystudentbinding',
            name='assigned_seats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
