# Generated by Django 5.2.5 on 2026-03-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0018_activitystudentbinding_assigned_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystudentbinding',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
