# Generated by Django 5.2.5 on 2026-03-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0019_activitystudentbinding_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitystudentbinding',
            name='analysis',
        ),
        migrations.AddField(
            model_name='activitypassenger',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitypassenger',
            name='pwd_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitypassenger',
            name='senior_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
