# Generated by Django 5.2.5 on 2026-04-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0022_studentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystudentbinding',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitystudentbinding',
            name='is_failed_due_to_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitystudentbinding',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitystudentbinding',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
