# Generated by Django 5.2.5 on 2026-04-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0023_activitystudentbinding_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='required_seat_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
