# Generated by Django 6.0 on 2026-05-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs_instructor', '0025_instructornotificationreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
