import os
import django
import random
from datetime import timedelta
from decimal import Decimal
from django.utils import timezone

# Set up Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'fbs_backend.settings')
django.setup()

from django.contrib.auth.models import User
from app.models import (
    Country, Airline, Airport, Aircraft, SeatClass, Route, Flight, Schedule,
    Seat, Students, AddOnType, AddOn, TaxType,
    PassengerTypeTaxRate, Booking, BookingDetail, PassengerInfo,
    Payment, TrackLog, CheckInDetail,
    InsuranceProvider, InsuranceBenefit, TravelInsurancePlan,
    MealCategory, MealOption, BaggageOption, AssistanceService,
    AirlineTax, AirportFee,
)
from fbs_instructor.models import (
    Instructor, Section, SectionEnrollment, Activity,
    UserSession
)


def seed_5():
    print("🚀 Seeding 5 records per table...\n")
    now = timezone.now()

    # ───────────────  USERS  ───────────────
    users = []
    for i in range(5):
        suffix = random.randint(1000, 9999)
        u = User.objects.create_user(
            username=f"usr_{i}_{suffix}",
            email=f"usr_{i}_{suffix}@ex.com",
            password="password123"
        )
        users.append(u)
    print("✅ Users: 5")

    # ───────────────  COUNTRIES  ───────────────
    countries = []
    for i in range(5):
        code = f"S{i}{random.randint(1,9)}"  # max 5 chars
        c, _ = Country.objects.get_or_create(
            code=code,
            defaults={'name': f"Seed Country {i} {random.randint(10,99)}", 'currency': 'PHP'}
        )
        countries.append(c)
    print("✅ Countries: 5")

    # ───────────────  AIRLINES  ───────────────
    airlines = []
    for i in range(5):
        code = f"SA{i}{random.randint(10,99)}"
        a, _ = Airline.objects.get_or_create(
            code=code,
            defaults={'name': f"Seed Airline {i} {random.randint(10,99)}"}
        )
        airlines.append(a)
    print("✅ Airlines: 5")

    # ───────────────  SEAT CLASSES  ───────────────
    seat_classes = []
    for a in airlines:
        sc, _ = SeatClass.objects.get_or_create(
            airline=a, name='Economy',
            defaults={'price_multiplier': Decimal('1.0')}
        )
        seat_classes.append(sc)
    print(f"✅ SeatClasses: {len(seat_classes)}")

    # ───────────────  AIRPORTS  ───────────────
    airports = []
    for i in range(5):
        code = f"P{i}{random.randint(10,99)}"
        ap, _ = Airport.objects.get_or_create(
            code=code,
            defaults={
                'name': f"Seed Airport {i}",
                'city': f"Seed City {i}",
                'country': countries[i],
                'airport_type': 'international'
            }
        )
        airports.append(ap)
    print("✅ Airports: 5")

    # ───────────────  AIRCRAFTS  ───────────────
    aircrafts = []
    for i in range(5):
        ac = Aircraft.objects.create(
            model=f"Seed Model {random.randint(100,999)}",
            capacity=150,
            airline=airlines[i]
        )
        aircrafts.append(ac)
    print("✅ Aircrafts: 5")

    # ───────────────  ROUTES  ───────────────
    routes = []
    for i in range(5):
        r = Route.objects.create(
            origin_airport=airports[i],
            destination_airport=airports[(i+1) % 5],
            base_price=Decimal(random.randint(1500, 3000))
        )
        routes.append(r)
    print("✅ Routes: 5")

    # ───────────────  FLIGHTS  ───────────────
    flights = []
    for i in range(5):
        f = Flight.objects.create(
            flight_number=f"SF{random.randint(1000, 9999)}",
            airline=airlines[i],
            aircraft=aircrafts[i],
            route=routes[i]
        )
        flights.append(f)
    print("✅ Flights: 5")

    # ───────────────  SCHEDULES (seats auto-generated by signal)  ───────────────
    schedules = []
    for i in range(5):
        s = Schedule.objects.create(
            flight=flights[i],
            departure_time=now + timedelta(days=i+5),
            arrival_time=now + timedelta(days=i+5, hours=1.5),
            status='Open',
            price=flights[i].route.base_price
        )
        schedules.append(s)
    print("✅ Schedules: 5 (seats auto-generated)")

    # ───────────────  BAGGAGE OPTIONS  ───────────────
    baggage_options = []
    weights = [0, 5, 10, 15, 20]
    for i, w in enumerate(weights):
        airline = airlines[i]
        bo, _ = BaggageOption.objects.get_or_create(
            airline=airline,
            weight_kg=w,
            defaults={
                'name': f"Baggage {w}kg",
                'price': Decimal(w * 50),
            }
        )
        baggage_options.append(bo)
    print("✅ BaggageOptions: 5")

    # ───────────────  ASSISTANCE SERVICES  ───────────────
    service_types = ['wheelchair', 'boarding', 'medical', 'unaccompanied_minor', 'other']
    for i, stype in enumerate(service_types):
        AssistanceService.objects.create(
            airline=airlines[i],
            name=f"Seed Assist {i}",
            service_type=stype,
            price=Decimal('0.00')
        )
    print("✅ AssistanceServices: 5")

    # ───────────────  MEAL CATEGORIES & OPTIONS  ───────────────
    meal_cat = MealCategory.objects.create(name=f"Seed Cat {random.randint(100,999)}")
    for i in range(5):
        MealOption.objects.create(
            airline=airlines[i],
            name=f"Seed Meal {i}",
            category=meal_cat,
            price=Decimal('250.00')
        )
    print("✅ MealCategory + MealOptions: 5")

    # ───────────────  ADD-ON TYPES & ADD-ONS  ───────────────
    for i in range(5):
        at = AddOnType.objects.create(name=f"Seed Type {random.randint(100,999)}")
        AddOn.objects.create(
            name=f"Seed Addon {i}",
            type=at,         # field is 'type', not 'addon_type'
            airline=airlines[i],
            price=Decimal('100.00')
        )
    print("✅ AddOnTypes & AddOns: 5 each")

    # ───────────────  TAX TYPES  ───────────────
    tax_types = []
    for i in range(5):
        code = f"TX{i}{random.randint(10,99)}"
        tt = TaxType.objects.create(
            name=f"Seed Tax {i} {random.randint(10,99)}",
            code=code,
            category='government'
        )
        tax_types.append(tt)
    print("✅ TaxTypes: 5")

    # ───────────────  AIRLINE TAXES  ───────────────
    for i in range(5):
        AirlineTax.objects.create(
            airline=airlines[i],
            tax_type=tax_types[i],
            amount=Decimal('50.00')
        )
    print("✅ AirlineTaxes: 5")

    # ───────────────  AIRPORT FEES  ───────────────
    for i in range(5):
        AirportFee.objects.create(
            airport=airports[i],
            tax_type=tax_types[i],
            amount=Decimal('100.00')
        )
    print("✅ AirportFees: 5")

    # ───────────────  STUDENTS  ───────────────
    students = []
    for i in range(5):
        stu = Students.objects.create(
            user=users[i],
            student_number=f"STU{random.randint(100000, 999999)}",
            first_name=f"SStu{i}",
            last_name=f"SLast{i}",
            email=f"sstu{i}_{random.randint(100,999)}@ex.com"
        )
        students.append(stu)
    print("✅ Students: 5")

    # ───────────────  INSTRUCTORS  ───────────────
    instructors = []
    for i in range(5):
        suffix = random.randint(1000, 9999)
        inst_user = User.objects.create_user(username=f"ins_{suffix}", password="password")
        ins = Instructor.objects.create(
            user=inst_user,
            instructor_id=f"SINS{suffix}",
            first_name=f"SIns{i}",
            last_name=f"SLast{i}",
            email=f"sins{suffix}@ex.com"
        )
        instructors.append(ins)
    print("✅ Instructors: 5")

    # ───────────────  SECTIONS & ENROLLMENT  ───────────────
    sections = []
    for i in range(5):
        sec = Section.objects.create(
            section_name=f"Seed Sec {i} {random.randint(100,999)}",
            section_code=f"SS{random.randint(1000,9999)}",
            semester="1st",
            academic_year="2025-2026",
            instructor=instructors[i].user
        )
        sections.append(sec)
        SectionEnrollment.objects.create(section=sec, student=students[i])
    print("✅ Sections & Enrollments: 5")

    # ───────────────  ACTIVITIES  ───────────────
    for i in range(5):
        Activity.objects.create(
            title=f"Seed Activity {i}",
            section=sections[i],
            due_date=now + timedelta(days=10),
            instructions="Seed instructions"
        )
    print("✅ Activities: 5")

    # ───────────────  PASSENGER INFO & BOOKINGS  ───────────────
    passengers = []
    for i in range(5):
        p = PassengerInfo.objects.create(
            first_name=f"SPass{i}",
            last_name=f"SLast{i}",
            passenger_type='Adult'
        )
        passengers.append(p)
        b = Booking.objects.create(
            user=users[i],
            total_amount=Decimal('2000.00'),
            status='confirmed'
        )
        bd = BookingDetail.objects.create(
            booking=b, passenger=p, schedule=schedules[i],
            price=schedules[i].price, status='confirmed'
        )
        Payment.objects.create(
            booking=b, amount=Decimal('2000.00'),
            method='Cash', status='Completed'
        )
        CheckInDetail.objects.create(booking_detail=bd, status='checked-in')
        TrackLog.objects.create(user=users[i], action="Seed Action")
    print("✅ Passengers, Bookings, Details, Payments, CheckIns, Logs: 5 each")

    # ───────────────  INSURANCE  ───────────────
    code = f"SI{random.randint(10,99)}"
    provider, _ = InsuranceProvider.objects.get_or_create(
        code=code, defaults={'name': "Seed Insurer"}
    )
    for i in range(5):
        benefit = InsuranceBenefit.objects.create(name=f"Seed Benefit {random.randint(100,999)}")
        plan = TravelInsurancePlan.objects.create(
            provider=provider,
            name=f"Seed Plan {random.randint(100,999)}",
            retail_price=Decimal(100)
        )
        plan.benefits.add(benefit)
    print("✅ Insurance: 5 benefits + 5 plans")

    # ───────────────  USER SESSIONS  ───────────────
    for i in range(5):
        UserSession.objects.create(
            user=users[i],
            session_token=f"tok_{random.randint(100000, 999999)}",
            role='student'
        )
    print("✅ UserSessions: 5")

    print("\n✨ Done! 5 records inserted into all major tables.")


if __name__ == "__main__":
    seed_5()
